### ISSUE TITLE
[TASK] - Footer Menu

### ISSUE THREAD

**Issue by MerseyAnimalHub-BM** [MerseyAnimalHub/Pet-Care-Website#15]
**URL**
All urls

**Summary of task**
Update the footer with links to policies.

**Task to-do list**

- [x] Add Cookie Policy
- [x] Add Privacy Policy
- [x] Add Terms & Conditions Policy

**Additional context**

**Comment by MerseyAnimalHub-BM** [comment]
Completed
